A=input("Enter Your Name: ")
B=input("Enter Your Friend Name: ")
A=A.upper()
B=B.upper()
AB=(A+B)
T=AB.count('T')
R=AB.count('R')
U=AB.count('U')
E=AB.count('E')
L=AB.count('L')
O=AB.count('O')
V=AB.count('V')
E=AB.count('E')
COUNT=T+R+U+E+L+O+V+E
print("Matching coutn in percent: ",(COUNT*10))
